local PRE_TOKENS, KEYWORDS

do
    local info = require("tokens")
    PRE_TOKENS, KEYWORDS = info[1], info[2]
end

local AST_SPEC = {
  VarDecl = {
    fields = { "type", "name", "value" }
  },

  binaryExpr = {
	fields = {"op", "left", "right"}
  },

  IntLiteral = {
    fields = { "value" }
  },

  VarRef = {
    fields = { "name" }
  }
}

local kinds = {
	PROGRAM = "__PROGRAM",
	BLOCK = "__BLOCK",
	FUNCTION_DECLARATION = "__FUNCTION_DECLARATION",
	WHILE = "__WHILE",
	IF = "__IF",
	FOR = "__FOR",
	RAW_DO = "__RAW_DO",
	LITERAL_BOOL = "__LITERAL_BOOL",
	CALL_EXPRESSION = "__CALL_EXPRESSION",
	CUSTOM_VAR_DECLARATION = "__CUSTOM_VAR_DECLARATION",
	STRUCT_DECLARATION = "__STRUCT_DECLARATION",
	VAR_DECLARATION = "__VAR_DECLARATION",
	VAR_REDEFINITION = "__VAR_REDEFINITION",
	VAR_ASSIGNMENT = "__VAR_ASSIGNMET",
	VAR_ASSIGNMENT_WITH_FIELDS = "__VAR_ASSIGNMENT_WITH_FIELDS",
	FIELD_VAR_REDEFINITION = "__FIELD_VAR_REDEFINITION",
	NULL_VAR_DECLARATION = "__NULL_VAR_DECLARATION",
	CUSTOM_NULL_VAR_DECLARATION = "__CUSTOM_NULL_VAR_DECLARATION",
	STRUCT_VAR_DECLARATION = "__STRUCT_VAR_DECLARATION",
	CUSTOM_STRUCT_VAR_DECLARATION = "__CUSTOM_STRUCT_VAR_DECLARATION",
	STRUCT_INIT = "__STRUCT_INIT",
	STRUCT_INIT_VAR_DECLARATION = "__STRUCT_INIT_VAR_DECLARATION",
	ARRAY = "__ARRAY",
	STRING_LITERAL = "__STRING_LITERAL",
	CHAR_LITERAL = "__CHAR_LITERAL",
	RETURN = "__RETURN",
	BINARY_EXPRESSION = "__BINARY_EXPRESSION",
	MODIFIER = "__MODIFIER",
	
	QUALIFICATOR = "__QUALIFICATOR",
	ARRAY_MODIFIER = "__ARRAY_MODIFIER",
	LITERAL = "__LITERAL",
	VAR_REF = "__VAR_REF",
	VAR_REF_WITH_FIELDS = "__VAR_REF_WITH_FIELDS",
	DEREF_VAR_REF = "__DEREF_VAR_REF",
	UNARY_EXPRESSION = "__UNARY_EXPRESSION",
	POINTER_MODIFIER = "__POINTER_MODIFIER",
	POINTER_DEREFERENCE = "__POINTER_DEREFERENCE",
	ADDRESS_OF = "__ADDRESS_OF",
	FIELD_ACCESS = "__FIELD_ACCESS",
	POINTER_FIELD_ACCESS = "__FIELD_ACCESS",
	INDEX_FIELD_ACCESS = "__INDEX_FIELD_ACCESS",
}

-- VAR DECLARATION

-- <type> <name> <equal> <expression>

return {AST_SPEC, kinds}
