local PRE_TOKENS, KEYWORDS

do
    local info = require("tokens")
    PRE_TOKENS, KEYWORDS = info[1], info[2]
end

local kinds = {
	PROGRAM = "__PROGRAM",
	
	RAW_TYPE = "__RAW_TYPE",

	FUNCTION_DECLARATION = "__FUNCTION_DECLARATION",
	FUNCTION_DECLARATION_PROTOTYPE = "__FUNCTION_DECLARATION_PROTOTYPE",
	STRUCT_DECLARATION = "__STRUCT_DECLARATION",
	STRUCT_DECLARATION_PROTOTYPE = "__STRUCT_DECLARATION_PROTOTYPE",
	VAR_DECLARATION = "__VAR_DECLARATION",
	VAR_DECLARATION_PROTOTYPE = "__VAR_DECLARATION_PROTOTYPE",
	STRUCT_VAR_DECLARATION = "__STRUCT_VAR_DECLARATION",
	STRUCT_INIT_VAR_DECLARATION = "__STRUCT_INIT_VAR_DECLARATION",

	VAR_ASSIGNMENT = "__VAR_ASSIGNMENT",
	
	RAW_SIZEOF = "__RAW_SIZEOF",
	VAR_SIZEOF = "__VAR_SIZEOF",
	
	RAW_DO = "__RAW_DO",
	IF = "__IF",
	ELSEIF = "__ELSEIF",
	WHILE = "__WHILE",
	FOR = "__FOR",
	BREAK = "__BREAK",
	EXTERN = "__EXTERN",
	RETURN = "__RETURN",
	VOID_RETURN = "__VOID_RETURN",
	
	LITERAL_INT = "__LITERAL_INT",
	LITERAL_FLOAT = "__LITERAL_FLOAT",
	LITERAL_BOOL = "__LITERAL_BOOL",
	LITERAL_STRING = "__LITERAL_STRING",
	LITERAL_CHAR = "__LITERAL_CHAR",
	
	CALL_EXPRESSION = "__CALL_EXPRESSION",

	BINARY_EXPRESSION = "__BINARY_EXPRESSION",
	UNARY_EXPRESSION = "__UNARY_EXPRESSION",
	
	STRUCT_INIT = "__STRUCT_INIT",
	ENUM_INIT = "__ENUM_INIT",

	ARRAY = "__ARRAY",

	MODIFIER = "__MODIFIER",
	ARRAY_MODIFIER = "__ARRAY_MODIFIER",
	POINTER_MODIFIER = "__POINTER_MODIFIER",
	QUALIFICATOR = "__QUALIFICATOR",
	CAST = "__CAST",

	VAR_REF = "__VAR_REF",
	VAR_REF_FIELDS = "__VAR_REF_WITH_FIELDS",

	POINTER_DEREFERENCE = "__POINTER_DEREFERENCE",
	ADDRESS_OF = "__ADDRESS_OF",

	FIELD_ACCESS = "__FIELD_ACCESS",
	POINTER_FIELD_ACCESS = "__POINTER_FIELD_ACCESS",
	INDEX_FIELD_ACCESS = "__INDEX_FIELD_ACCESS",

	EXPRESSION = "__EXPRESSION",
}

return {AST_SPEC, kinds}
