local e = {
	SUCESS = 0,
	
	GENERIC_LEXER_ERROR = 1,
	GENERIC_SINTAX_ERROR = 2,
	GENERIC_SEMANTIC_ERROR = 3,

	-- LEXER
	UNKNOW_CHARACTER = 10,
	INVALID_TOKEN = 11,
	INVALID_SCAPE_SEQUNCE = 12,
	INVALID_CHAR = 13,
	NO_TOKEN_KEY = 14,
	NIL_TOKEN_BUFFER = 15,
	UNFINISHED_STRING = 16,
	UNFINISHED_CHAR = 17,
	UNFINISHED_COMMENT = 18,

	--parser
	EXPECTED = 20,
	EXPECTED_CUSTOM = 21,
	EXPECTED_TOKEN = 22,
	EXPECTED_STR = 23,
	
	CLOSE_GLOBAL_SCOPE = 24,
	UNCLOSED_SCOPE = 25,
	
	IMCOMPLETE_EXPRESION = 26,
	INCOMPLETE_CONSUME = 27,
	INCOMPLETE_FUNCTION = 28,
	
	NO_FUNCTION = 29,

	INVALID_EXPRESSION = 30,

	FAR_QUALIFIER = 31,
	
	INCOMPATIBLE_QUALIFIER = 32,
	
	DOUBLE_LONG_LONG = 33,
	LONG_LONG_PLUS = 34,
	
	SHORT_PLUS = 35,
	
	LONG_SHORT = 36,

	SINGNED_UNSIGNED = 37,
	
	EMPTY_STRUCT = 38,
	INVALID_STRUCT = 39,

	EMPTY_ENUM = 40,

	UNEXPECTED_ELSEIF = 41,
	UNEXPECTED_ELSE = 42,

	DUPLICATED_ELSE = 43,

	INVALID_STATEMENT = 44,

	--KEYWORD_AS_NAME = 21,

}

return e